/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "practica.h"

bool_t
xdr_Posicion(xdrs, objp)
	XDR *xdrs;
	Posicion *objp;
{

	if (!xdr_int(xdrs, &objp->x))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->y))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InfoAuto(xdrs, objp)
	XDR *xdrs;
	InfoAuto *objp;
{

	if (!xdr_Posicion(xdrs, &objp->posicion_auto))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->tipo, 10))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->tarifa))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->placa, 7))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_InfoServicio(xdrs, objp)
	XDR *xdrs;
	InfoServicio *objp;
{

	if (!xdr_int(xdrs, &objp->viajes_realizados))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->autos_libres))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->ganancia))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_terminarviaje_1_argument(xdrs, objp)
	XDR *xdrs;
	terminarviaje_1_argument *objp;
{
	if (!xdr_Posicion(xdrs, &objp->arg1))
		return (FALSE);
	if (!xdr_float(xdrs, &objp->arg2))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->arg3, ~0))
		return (FALSE);
	return (TRUE);
}
