/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "practica.h"
#include "test.h"
#include <stdio.h>

void
    display_prg_1(host) char *host;
{
    CLIENT *clnt;
    InfoAuto *result_1;
    Posicion solicitarviaje_1_arg1;
    void *result_2;
    Posicion terminarviaje_1_arg1;
    float terminarviaje_1_arg2;
    char *terminarviaje_1_arg3;
    InfoServicio *result_3;
    clnt = clnt_create(host, DISPLAY_PRG, DISPLAY_VER, "utc");
    if (clnt == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
    result_1 = solicitarviaje_1(solicitarviaje_1_arg1, clnt);
    if (result_1 == NULL)
    {
        clnt_perror(clnt, "call failed:");
    }
    result_2 = terminarviaje_1(terminarviaje_1_arg1, terminarviaje_1_arg2, terminarviaje_1_arg3, clnt);
    if (result_2 == NULL)
    {
        clnt_perror(clnt, "call failed:");
    }
    result_3 = estadoservicio_1(clnt);
    if (result_3 == NULL)
    {
        clnt_perror(clnt, "call failed:");
    }
    clnt_destroy(clnt);
}

void create_client(char *host, CLIENT *client)
{
    client = clnt_create(host, DISPLAY_PRG, DISPLAY_VER, "tcp");
    if (client == NULL)
    {
        clnt_pcreateerror(host);
        exit(1);
    }
}

void requestTrip(host) char *host;
{
    CLIENT *client;
    InfoAuto *result;
    Posicion posicionPasajero;
    Posicion posicionFinal;
    float distanciaViaje;

    create_client(host, client);

    // Asigar valores a la posición del pasajero.
    posicionPasajero.x = randomPosicion();
    posicionPasajero.y = randomPosicion();

    // LLAMADA A PROCEDIMIENTO REMOTO
    result = solicitarviaje_1(posicionPasajero, client);

    // Si el resultado es nulo, no existen autos disponibles.
    if (result == NULL)
    {
        clnt_perror(client, "call failed:");
    }

    // random posicion final
    posicionFinal.x = randomPosicion();
    posicionFinal.y = randomPosicion();

    distanciaViaje = calcularDistancia(posicionPasajero, posicionFinal);

    clnt_destroy(client);
}

void finishTrip(Posicion posicionFinal, float distanciaViaje, InfoAuto *info_auto, CLIENT *client)
{
    float costoViaje;
    char *placasAuto;

    // Sleep proporcional al viaje
    sleep((int)distanciaViaje);

    costoViaje = distanciaViaje * info_auto->tarifa;
    placasAuto = info_auto->placa;

    // LLAMADA A PROCEDIMIENTO REMOTO
    terminarviaje_1(posicionFinal, costoViaje, placasAuto, client);
}

void requestStatus(host) char *host;
{
    InfoServicio *result;
    CLIENT *client;

    create_client(host, client);

    // LLAMADA A PROCEDIMIENTO REMOTO
    result = estadoservicio_1(client);

    if (result == NULL)
    {
        clnt_perror(client, "call failed:");
    }

    clnt_destroy(client);
}

void printStatus(InfoServicio *info_servicio)
{
    printf("Viajes realizados: %d\n", info_servicio->viajes_realizados);
    printf("Autos libres: %d\n", info_servicio->autos_libres);
    printf("Ganancias: %.2f\n", info_servicio->ganancia);

    free(info_servicio);
}

main(argc, argv) int argc;
char *argv[];
{
    char *host;
    int op;

    if (argc < 3)
    {
        printf("usage: %s server_host option\n", argv[0]);
        printf("1. Solicitar Viaje\n");
        printf("2. Estado del Servicio\n");
        exit(1);
    }
    host = argv[1];
    op = atoi(argv[2]);

    switch (op)
    {
    case 1:
        requestTrip(host);
        break;
    case 2:
        requestStatus(host);
        break;
    default:    
        printf("Invalid option\n");
        break;
    }
}
